"""PX4 custom mode constants and MAVLink helpers."""

from __future__ import annotations

# PX4 custom main modes (matches px4_custom_mode.h)
PX4_CUSTOM_MAIN_MODE_MANUAL = 1
PX4_CUSTOM_MAIN_MODE_ALTCTL = 2
PX4_CUSTOM_MAIN_MODE_POSCTL = 3
PX4_CUSTOM_MAIN_MODE_AUTO = 4
PX4_CUSTOM_MAIN_MODE_ACRO = 5
PX4_CUSTOM_MAIN_MODE_OFFBOARD = 6
PX4_CUSTOM_MAIN_MODE_STABILIZED = 7
PX4_CUSTOM_MAIN_MODE_RATTITUDE_LEGACY = 8
PX4_CUSTOM_MAIN_MODE_SIMPLE = 9

PX4_CUSTOM_SUB_MODE_AUTO_READY = 1
PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF = 2
PX4_CUSTOM_SUB_MODE_AUTO_LOITER = 3
PX4_CUSTOM_SUB_MODE_AUTO_MISSION = 4
PX4_CUSTOM_SUB_MODE_AUTO_RTL = 5
PX4_CUSTOM_SUB_MODE_AUTO_LAND = 6
PX4_CUSTOM_SUB_MODE_AUTO_RESERVED_DO_NOT_USE = 7
PX4_CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET = 8
PX4_CUSTOM_SUB_MODE_AUTO_PRECLAND = 9

# Position-target type_mask bits (ignore when set)
IGNORE_PX = 1
IGNORE_PY = 2
IGNORE_PZ = 4
IGNORE_VX = 8
IGNORE_VY = 16
IGNORE_VZ = 32
IGNORE_AFX = 64
IGNORE_AFY = 128
IGNORE_AFZ = 256
FORCE_SET = 512
IGNORE_YAW = 1024
IGNORE_YAW_RATE = 2048

POSITION_TARGET_TYPEMASK_POS_YAW = (
    IGNORE_VX | IGNORE_VY | IGNORE_VZ | IGNORE_AFX | IGNORE_AFY | IGNORE_AFZ | IGNORE_YAW_RATE
)
POSITION_TARGET_TYPEMASK_POS_ONLY = POSITION_TARGET_TYPEMASK_POS_YAW | IGNORE_YAW
POSITION_TARGET_TYPEMASK_YAW_ONLY = (
    IGNORE_PX
    | IGNORE_PY
    | IGNORE_PZ
    | IGNORE_VX
    | IGNORE_VY
    | IGNORE_VZ
    | IGNORE_AFX
    | IGNORE_AFY
    | IGNORE_AFZ
    | IGNORE_YAW_RATE
)


def encode_custom_mode(main_mode: int, sub_mode: int = 0) -> int:
    """Pack PX4 custom mode into the 32-bit custom_mode field of HEARTBEAT / SET_MODE."""
    return (main_mode << 16) | (sub_mode << 24)


MODE_TABLE = {
    "manual": (PX4_CUSTOM_MAIN_MODE_MANUAL, 0),
    "altctl": (PX4_CUSTOM_MAIN_MODE_ALTCTL, 0),
    "posctl": (PX4_CUSTOM_MAIN_MODE_POSCTL, 0),
    "acro": (PX4_CUSTOM_MAIN_MODE_ACRO, 0),
    "offboard": (PX4_CUSTOM_MAIN_MODE_OFFBOARD, 0),
    "stabilized": (PX4_CUSTOM_MAIN_MODE_STABILIZED, 0),
    "auto:mission": (PX4_CUSTOM_MAIN_MODE_AUTO, PX4_CUSTOM_SUB_MODE_AUTO_MISSION),
    "auto:loiter": (PX4_CUSTOM_MAIN_MODE_AUTO, PX4_CUSTOM_SUB_MODE_AUTO_LOITER),
    "auto:rtl": (PX4_CUSTOM_MAIN_MODE_AUTO, PX4_CUSTOM_SUB_MODE_AUTO_RTL),
    "auto:takeoff": (PX4_CUSTOM_MAIN_MODE_AUTO, PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF),
    "auto:land": (PX4_CUSTOM_MAIN_MODE_AUTO, PX4_CUSTOM_SUB_MODE_AUTO_LAND),
    "auto:precland": (PX4_CUSTOM_MAIN_MODE_AUTO, PX4_CUSTOM_SUB_MODE_AUTO_PRECLAND),
}
